### PR TITLE
Add Enterprise ELK stuff (for #SG-3353)

### PR DESCRIPTION
**Pull request by khosrow**
Added separate `docker-compose` file to start the Enterprise ELK stack. Also appended the README file with contents of the README from the *enterprise-elk* repo.

### CODE REVIEW

**Comment by david-richer-adsk** [comment]
@guillaume-brossard-adsk Do we want it for 7.8 or 7.9 ?

**Comment by khosrow** [comment]
So does that mean we're prepared to "open source" the **enterprise-elk** repository?

**Comment by david-richer-adsk** [comment]
I think I would prefer 2 subfolder in this repository

**Comment by khosrow** [comment]
How do you mean? Something like this?
1. shotgun
2. elk

I was thinking of closing this PR and just leaving the ELK stuff in its own repo with a link to it from here.

**Comment by david-richer-adsk** [comment]
After a second tough, better to keep them in different repo and assemble them in https://github.com/shotgunsoftware/shotgun/blob/master/files_docker/pkg/package-app.sh

**Comment by khosrow** [comment]
Closing this PR. As discussed above, we will keep the ELK stuff in its own repository and we'll assemble them when building the Shotgun Enterprise package.

**Pull request closed without merging**
